package exceptionHandling0;
import java.util.*;
public class Addition {
	public static void main(String[] args) {
		try {
			Scanner scn=new Scanner(System.in);
			System.out.println("enter first no. : ");
			int a=scn.nextInt();
			System.out.println("enter the second no. : ");
			int b=scn.nextInt();
			System.out.println("add : "+(a+b));
		}
		catch(ArrayIndexOutOfBoundsException e) {
			System.out.println("add : "+(4+5));
		}
		catch(NumberFormatException e) {
			System.out.println("add : "+(6+7));
		}
		catch(ArithmeticException e) {
			System.out.println("add : "+(8+9));
		}
		catch(InputMismatchException e) {
			System.out.println("add : "+(10+11));
		}

	}

}
